"""
Phyrobot — Phase 2: AI Signal Validation Layer
────────────────────────────────────────────────────────
Uses Groq (LLaMA 3 70B) as a second-opinion analyst that:

  1. Reviews the full signal context (regime, group scores, price action)
  2. Identifies hidden risks the scoring engine can't see
  3. Returns a structured verdict: APPROVE / DOWNGRADE / REJECT
  4. Adjusts confidence level and quality score based on AI verdict
  5. Adds a human-readable AI rationale to the Telegram message

The AI does NOT replace the scoring engine — it acts as a senior analyst
reviewing a junior analyst's work. The scoring engine sets the floor,
the AI raises or lowers it.

Architecture:
  Phase 1 (signal_engine.py) → quality_result dict
  Phase 2 (ai_validator.py)  → enriched quality_result dict
  bot.py                     → sends final signal

Groq model: llama3-70b-8192 (fast, cheap, strong reasoning)
Fallback: if Groq unavailable, Phase 1 result passes through unchanged
"""

import json
import logging
import time
import hashlib
from typing import Optional

log = logging.getLogger(__name__)

# ─── CONFIG ───────────────────────────────────────────────────────────────────
AI_VALIDATION_ENABLED  = True    # toggle off to bypass AI (falls back to Phase 1)
AI_TIMEOUT_SECONDS     = 8       # max wait for Groq response
AI_MIN_QUALITY_TO_CALL = 40      # don't call AI for low-quality signals (saves API calls)
AI_VETO_THRESHOLD      = 30      # AI confidence below this = REJECT
AI_BOOST_THRESHOLD     = 70      # AI confidence above this = confidence upgrade possible
AI_CACHE_TTL           = 300     # cache same signal context for 5 minutes (avoid spam)

# ─── SIGNAL CACHE (prevents duplicate AI calls for same signal) ────────────────
_ai_cache: dict = {}

def _cache_key(symbol: str, direction: str, quality_score: float) -> str:
    raw = f"{symbol}_{direction}_{int(quality_score)}"
    return hashlib.md5(raw.encode()).hexdigest()[:12]

def _get_cached(key: str) -> Optional[dict]:
    entry = _ai_cache.get(key)
    if entry and time.time() - entry["ts"] < AI_CACHE_TTL:
        return entry["result"]
    return None

def _set_cached(key: str, result: dict):
    _ai_cache[key] = {"result": result, "ts": time.time()}


# ─── CONTEXT BUILDER ──────────────────────────────────────────────────────────
def build_ai_context(
    symbol: str,
    quality_result: dict,
    price: float,
    funding_rate: float,
    news_sentiment: str = "NEUTRAL",
    news_points: list = None,
) -> str:
    """
    Build a compact, information-dense prompt context for the AI.
    Keeps token count low while giving the AI everything it needs.
    """
    direction     = quality_result.get("direction", "NEUTRAL")
    quality       = quality_result.get("quality_score", 0)
    confidence    = quality_result.get("confidence", "LOW")
    regime        = quality_result.get("regime", {})
    group_scores  = quality_result.get("group_scores", {})
    signals       = quality_result.get("signals", [])
    confluence    = quality_result.get("confluence_groups", 0)
    filters       = quality_result.get("filters", {})

    regime_str   = regime.get("regime", "UNKNOWN")
    adx_val      = regime.get("adx", 0)
    slope        = regime.get("slope", 0)
    atr_pct      = filters.get("volatility", {}).get("atr_pct", 0)
    tf_aligned   = filters.get("tf_alignment", {}).get("pass", False)

    # Format group scores as clean percentages
    gs_str = " | ".join([
        f"{k.upper()[:4]}:{'+' if v >= 0 else ''}{v:.2f}"
        for k, v in group_scores.items()
    ])

    # Top signals (max 6)
    sigs_str = "\n".join([f"  - {s}" for s in signals[:6]])

    # News
    news_str = f"Market news sentiment: {news_sentiment}"
    if news_points:
        news_str += "\n" + "\n".join([f"  - {p}" for p in news_points[:3]])

    prompt = f"""You are a professional crypto futures trader and risk analyst reviewing a trading signal generated by a quantitative algorithm.

SIGNAL CONTEXT:
  Symbol: {symbol}
  Direction: {direction}
  Entry Price: ${price:.4f}
  Algorithm Quality Score: {quality}/100 ({confidence})
  Confluence: {confluence}/5 indicator groups agree
  Timeframe Aligned: {"YES" if tf_aligned else "NO"}

MARKET REGIME:
  Regime: {regime_str}
  ADX Strength: {adx_val}
  EMA50 Slope: {slope:+.3f}%
  ATR Volatility: {atr_pct:.2f}% of price

INDICATOR GROUP SCORES (-1.0 bearish to +1.0 bullish):
  {gs_str}

KEY SIGNALS DETECTED:
{sigs_str}

FUNDING RATE: {funding_rate*100:.4f}% (positive = longs paying shorts)

{news_str}

YOUR TASK:
Analyze this signal as a senior trader would. Consider:
1. Does the regime support this signal type?
2. Are there any conflicting signals or hidden risks?
3. Is the funding rate a concern (extreme positive = crowded long, extreme negative = crowded short)?
4. Does the confluence and quality score justify the trade?
5. Is there any reason this signal could be a false positive?

Respond ONLY with valid JSON in this exact format, no other text:
{{
  "verdict": "APPROVE" | "DOWNGRADE" | "REJECT",
  "ai_confidence": <integer 0-100>,
  "risk_level": "LOW" | "MEDIUM" | "HIGH",
  "rationale": "<one concise sentence explaining your verdict>",
  "key_risk": "<one sentence — the biggest risk with this trade>",
  "suggested_action": "<one actionable sentence for the trader>"
}}"""

    return prompt


# ─── AI VALIDATOR ─────────────────────────────────────────────────────────────
def validate_signal_with_ai(
    groq_client,
    symbol: str,
    quality_result: dict,
    price: float,
    funding_rate: float = 0.0,
    news_sentiment: str = "NEUTRAL",
    news_points: list = None,
) -> dict:
    """
    Core AI validation function. Calls Groq and returns enriched result.

    Returns:
    {
      "verdict": "APPROVE" | "DOWNGRADE" | "REJECT" | "BYPASS",
      "ai_confidence": int 0-100,
      "risk_level": "LOW" | "MEDIUM" | "HIGH",
      "rationale": str,
      "key_risk": str,
      "suggested_action": str,
      "final_confidence": "HIGH" | "MEDIUM" | "LOW",
      "final_quality": float,
      "ai_used": bool,
    }
    """
    default = {
        "verdict": "BYPASS",
        "ai_confidence": 50,
        "risk_level": "MEDIUM",
        "rationale": "AI validation bypassed",
        "key_risk": "Unknown",
        "suggested_action": "Follow scoring engine signal",
        "final_confidence": quality_result.get("confidence") or "MEDIUM",
        "final_quality": quality_result.get("quality_score") or quality_result.get("abs_score", 0),
        "ai_used": False,
    }

    if not AI_VALIDATION_ENABLED or groq_client is None:
        return default

    quality = quality_result.get("quality_score") or quality_result.get("abs_score", 0)
    if quality < AI_MIN_QUALITY_TO_CALL:
        default["rationale"] = f"Quality too low for AI review ({quality}/100)"
        return default

    # Cache check
    cache_key = _cache_key(symbol, quality_result.get("direction", ""), quality)
    cached = _get_cached(cache_key)
    if cached:
        log.info(f"AI cache hit for {symbol}")
        return cached

    try:
        prompt = build_ai_context(
            symbol, quality_result, price, funding_rate,
            news_sentiment, news_points or []
        )

        response = groq_client.chat.completions.create(
            model="llama3-70b-8192",
            max_tokens=400,
            temperature=0.1,        # low temperature = consistent, analytical responses
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a disciplined crypto futures risk analyst. "
                        "You respond ONLY with valid JSON. No markdown, no explanation outside JSON. "
                        "Be conservative — when in doubt, DOWNGRADE not APPROVE."
                    )
                },
                {"role": "user", "content": prompt}
            ],
        )

        raw = response.choices[0].message.content.strip()

        # Strip any accidental markdown fences
        if "```" in raw:
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        raw = raw.strip()

        ai_data = json.loads(raw)

        # Validate required fields
        verdict          = ai_data.get("verdict", "BYPASS")
        ai_confidence    = int(ai_data.get("ai_confidence", 50))
        risk_level       = ai_data.get("risk_level", "MEDIUM")
        rationale        = ai_data.get("rationale", "")
        key_risk         = ai_data.get("key_risk", "")
        suggested_action = ai_data.get("suggested_action", "")

        if verdict not in ("APPROVE", "DOWNGRADE", "REJECT"):
            verdict = "BYPASS"

        # ── Compute final confidence & quality adjustment ─────────────────
        original_quality     = quality_result.get("quality_score", 0)
        original_confidence  = quality_result.get("confidence", "MEDIUM")

        if verdict == "APPROVE" and ai_confidence >= AI_BOOST_THRESHOLD:
            # AI strongly approves — boost quality slightly, maintain or upgrade confidence
            final_quality = min(100, original_quality * 1.15)
            if original_confidence == "MEDIUM" and ai_confidence >= 80:
                final_confidence = "HIGH"
            else:
                final_confidence = original_confidence

        elif verdict == "DOWNGRADE":
            # AI sees risks — reduce quality, downgrade confidence
            penalty = (100 - ai_confidence) / 100  # higher penalty for lower AI confidence
            final_quality = original_quality * (1 - penalty * 0.4)
            final_confidence = "MEDIUM" if original_confidence == "HIGH" else "LOW"

        elif verdict == "REJECT" or ai_confidence < AI_VETO_THRESHOLD:
            # AI veto — quality collapses
            final_quality    = original_quality * 0.3
            final_confidence = "LOW"
            verdict          = "REJECT"

        else:
            # BYPASS or neutral
            final_quality    = original_quality
            final_confidence = original_confidence

        result = {
            "verdict":          verdict,
            "ai_confidence":    ai_confidence,
            "risk_level":       risk_level,
            "rationale":        rationale,
            "key_risk":         key_risk,
            "suggested_action": suggested_action,
            "final_confidence": final_confidence,
            "final_quality":    round(final_quality, 1),
            "ai_used":          True,
        }

        _set_cached(cache_key, result)
        log.info(
            f"AI verdict for {symbol}: {verdict} | "
            f"AI conf: {ai_confidence} | "
            f"Risk: {risk_level} | "
            f"Final quality: {final_quality:.1f}"
        )
        return result

    except json.JSONDecodeError as e:
        log.error(f"AI JSON parse error for {symbol}: {e}")
        return default
    except Exception as e:
        log.error(f"AI validation error for {symbol}: {e}")
        return default


# ─── ASYNC WRAPPER ────────────────────────────────────────────────────────────
async def validate_signal_async(
    groq_client,
    symbol: str,
    quality_result: dict,
    price: float,
    funding_rate: float = 0.0,
    news_sentiment: str = "NEUTRAL",
    news_points: list = None,
) -> dict:
    """
    Async wrapper — runs AI validation in thread pool to avoid blocking event loop.
    """
    import asyncio
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(
        None,
        lambda: validate_signal_with_ai(
            groq_client, symbol, quality_result, price,
            funding_rate, news_sentiment, news_points
        )
    )


# ─── SIGNAL ENRICHMENT ────────────────────────────────────────────────────────
def enrich_signal_with_ai(analysis_result: dict, ai_result: dict) -> dict:
    """
    Merge the Phase 1 analysis result with the Phase 2 AI verdict.
    Returns an enriched result dict ready for format_signal().
    """
    enriched = dict(analysis_result)

    verdict       = ai_result.get("verdict", "BYPASS")
    final_conf    = ai_result.get("final_confidence", analysis_result.get("confidence", "MEDIUM"))
    final_quality = ai_result.get("final_quality", analysis_result.get("quality", {}).get("quality_score", 0))
    ai_used       = ai_result.get("ai_used", False)

    # If AI rejected the signal, mark as NEUTRAL so it won't fire
    if verdict == "REJECT":
        enriched["direction"]  = "NEUTRAL"
        enriched["confidence"] = "LOW"
        enriched["ai_reject_reason"] = ai_result.get("rationale", "AI rejected signal")
        enriched["ai_result"]  = ai_result
        return enriched

    # Apply AI adjustments
    enriched["confidence"] = final_conf
    enriched["abs_score"]  = final_quality
    enriched["score"]      = final_quality if analysis_result.get("direction") == "LONG" else -final_quality
    enriched["ai_result"]  = ai_result

    # Add AI signals to the signal list
    if ai_used:
        ai_signals = []
        if ai_result.get("rationale"):
            ai_signals.append(f"🤖 AI: {ai_result['rationale']}")
        if ai_result.get("key_risk"):
            ai_signals.append(f"⚠ Risk: {ai_result['key_risk']}")
        enriched["signals"] = ai_signals + enriched.get("signals", [])

    return enriched


# ─── TELEGRAM MESSAGE FORMATTER ADDON ─────────────────────────────────────────
def format_ai_block(ai_result: dict) -> str:
    """
    Returns a formatted Telegram message block for the AI verdict.
    Append this to the existing format_signal() output.
    """
    if not ai_result or not ai_result.get("ai_used"):
        return ""

    verdict    = ai_result.get("verdict", "BYPASS")
    ai_conf    = ai_result.get("ai_confidence", 0)
    risk       = ai_result.get("risk_level", "MEDIUM")
    rationale  = ai_result.get("rationale", "")
    key_risk   = ai_result.get("key_risk", "")
    suggestion = ai_result.get("suggested_action", "")

    verdict_emoji = {
        "APPROVE":   "✅",
        "DOWNGRADE": "⚠",
        "REJECT":    "🚫",
        "BYPASS":    "⏭",
    }.get(verdict, "🤖")

    risk_emoji = {
        "LOW":    "🟢",
        "MEDIUM": "🟡",
        "HIGH":   "🔴",
    }.get(risk, "🟡")

    msg  = "\n🤖 *AI Analyst Verdict*\n"
    msg += f"{verdict_emoji} *{verdict}* | AI Confidence: `{ai_conf}%` | {risk_emoji} Risk: {risk}\n"
    if rationale:
        msg += f"📋 {rationale}\n"
    if key_risk:
        msg += f"⚠ Key Risk: {key_risk}\n"
    if suggestion:
        msg += f"💡 {suggestion}\n"

    return msg


# ─── FULL PIPELINE RUNNER ─────────────────────────────────────────────────────
async def run_full_pipeline(
    symbol: str,
    fetch_ohlcv_fn,
    coin_labels: dict,
    groq_client,
    exchange,
    news_context: dict = None,
) -> dict:
    """
    Complete Phase 1 + Phase 2 pipeline in one call.
    Replaces the original analyze() function entirely.

    Usage in bot.py:
        from ai_validator import run_full_pipeline
        r = await run_full_pipeline(symbol, fetch_ohlcv, COIN_LABELS, ai_client, exchange, news_context)
    """
    from signal_engine import analyze_v2

    # ── Phase 1: Scoring engine ───────────────────────────────────────────
    r = analyze_v2(symbol, fetch_ohlcv_fn, coin_labels)

    # ── Funding rate ──────────────────────────────────────────────────────
    try:
        funding     = exchange.fetch_funding_rate(symbol)
        r["funding"] = float(funding["fundingRate"]) if funding else 0
    except Exception:
        r["funding"] = 0

    # ── Skip AI if signal already NEUTRAL after Phase 1 ──────────────────
    if r["direction"] == "NEUTRAL":
        r["ai_result"] = {"verdict": "BYPASS", "ai_used": False}
        return r

    # ── Phase 2: AI validation ────────────────────────────────────────────
    news_sentiment = (news_context or {}).get("sentiment", "NEUTRAL")
    news_points    = (news_context or {}).get("key_points", [])

    quality_data = r.get("quality") or {}
    quality_data["quality_score"] = r.get("abs_score", 0)
    quality_data["direction"] = r.get("direction", "NEUTRAL")
    quality_data["confidence"] = r.get("confidence", "LOW")

    ai_result = await validate_signal_async(
        groq_client, symbol,
        quality_data,
        r["price"], r["funding"],
        news_sentiment, news_points,
    )

    # ── Merge results ─────────────────────────────────────────────────────
    r = enrich_signal_with_ai(r, ai_result)

    # ── Classify signal type (MOMENTUM/REVERSAL) using existing function ──
    # This is still done by classify_signal() in bot.py using df_4h
    # We pass through the data needed for it
    return r
